eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
spring:
   rabbitmq:
    host: rattlesnake.rmq.cloudamqp.com
    port: 5672
    username: oaetctqn
    virtual-host: oaetctqn
    password: kupW2TEwoZ_tp_yPpXfapR_DAnuQQbIU
